version: 1

before:
  hooks:
    - go mod tidy
    - go mod download
    #- go generate ./...

builds:
- id: pkgctl
  main: main.go
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    #- freebsd
    - linux
    #- openbsd
    #- windows
  goarch:
    #- '386'
    - amd64
    #- arm
    - arm64
  ignore:
    - goarch: arm
      goos: windows
    - goarch: arm64
      goos: freebsd
    - goarch: arm64
      goos: windows
    - goarch: arm64
      goos: openbsd
  mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
- format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
  name_template: >-
    {{ .ProjectName }}_
    {{ .Os }}_
    {{- if eq .Arch "amd64"}}aarch64
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - none*
  # use zip for windows archives
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
